// #include "min_heap.h"
// void testHeap()
// {	

//     MinHeap<int> h(11);
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
//     Debug::printf(" %x\n", h.extractMin());
// 	int three = 3;
// 	int two = 2;
// 	int one = 1;
// 	int fifteen = 15;
// 	int five = 5;
// 	int four = 4;
// 	int fortyfive = 45;
//     h.insertKey(&three, 3);
//     h.printHeap();
//     h.insertKey(&two ,2);
//     h.printHeap();
//     //h.deleteKey(&one,1);
//     h.insertKey(&fifteen, 15);
//     h.printHeap();
//     h.insertKey(&five, 5);
//     h.printHeap();
//     h.insertKey(&four, 4);
//     h.printHeap();
//     h.insertKey(&two ,2);
//     h.printHeap();
//     h.insertKey(&fortyfive, 45);
//     h.printHeap();
//     h.insertKey(&one, 1);
//     h.printHeap();
//     h.insertKey(&one, 1);
//     h.printHeap();
//     h.insertKey(&one, 1);
//     h.printHeap();
//     Debug::printf(" %d\n", *h.extractMin());
//     h.printHeap();
//     Debug::printf("%d\n", *h.extractMin());
//     h.printHeap();
//     Debug::printf("%d\n", *h.extractMin());
//     h.printHeap();
//     Debug::printf("%d\n", *h.extractMin());
//     h.printHeap();
//     Debug::printf("%d\n", *h.extractMin());
//     h.printHeap();
//     Debug::printf("%d\n", *h.extractMin());
//     Debug::printf("%d\n", *h.extractMin());
//     Debug::printf("%d\n", *h.extractMin());
//     Debug::printf("%d\n", *h.extractMin());
//     Debug::printf("%d\n", *h.extractMin());
//     Debug::printf("%d\n", h.extractMin());
//     Debug::printf("%d\n", h.extractMin());
//     Debug::printf("%d\n", h.extractMin());
//     Debug::printf("%d\n", h.extractMin());
//     Debug::printf("%d\n", h.extractMin());
//     Debug::printf("%d\n", h.extractMin());
// }